<?php
$additionalCssClasses = $block->getInvertedColor() ? ' inverted-color' : '';
?>
<div class="banner-widget <?= $escaper->escapeHtmlAttr($additionalCssClasses) ?>">
    <div class="banner-wrapper">
        <?php if ($block->getCssStyles()): ?>
            <style>
                <?= $block->getCssStyles() ?>
            </style>
        <?php endif; ?>
        <div class="banner-image">
            <?php
                $largeImageUrl = $block->getLargeImage();
                $mediumImageUrl = $block->getMediumImage();
                $smallImageUrl = $block->getSmallImage();
                $alt = $escaper->escapeHtml($block->getLabel())
            ?>
            <picture>
                <source type="image/jpeg" media="(max-width: 320px)" srcset="<?= $escaper->escapeUrl($smallImageUrl) ?>">
                <source type="image/jpeg" media="(max-width: 767px)" srcset="<?= $escaper->escapeUrl($mediumImageUrl) ?>">
                <source type="image/jpeg" media="(min-width: 768px)" srcset="<?= $escaper->escapeUrl($largeImageUrl) ?>">
                <img src="<?= $escaper->escapeUrl($largeImageUrl) ?>" alt="<?= $escaper->escapeHtmlAttr($alt) ?>" loading="lazy" />
            </picture>
        </div>
        <div class="banner-content" >
            <div class="banner-header">
                <strong><?= $escaper->escapeHtml($block->getHeading()) ?></strong>
            </div>

            <?php if ($block->getSubtitle()): ?>
                <div class="banner-subtitle">
                    <em><?= $escaper->escapeHtml($block->getSubtitle()) ?></em>
                </div>
            <?php endif; ?>

            <?php if ($block->getDescription()): ?>
                <div class="banner-text">
                    <?= $escaper->escapeHtml($block->getDescription(), $block->getAllowedHtmlTags()) ?>
                </div>
            <?php endif; ?>
            <?php if ($block->getHref() && $block->getLabel()): ?>
                <div class="banner-buttons">
                    <div class="banner-primary">
                        <a class="action primary" <?= $block->getLinkAttributes() ?>>
                            <span><?= $escaper->escapeHtml($block->getLabel()) ?></span>
                        </a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
